### PR TITLE
feat: option region for VerifySesEmailAddress

### LINKED ISSUE #214: Deploying VerifySesEmailAddress to another region
As per [this comment](https://github.com/seeebiii/ses-verify-identities/issues/212#issuecomment-856768594), it would be great to be able to deploy the VerifySesEmailAddress construct in another AWS region that the stack region.

To be consistent, I also tried to apply the same mechanism to VerifySesDomain, however, it seems to be a little more complicated because of the SNS topic that must probably be in the same region as the email address. Here is the error I had: `Received response status [FAILED] from custom resource. Message returned: SNS topic arn:aws:sns:{CUSTOM_REGION}:{ACCOUNT_ID}:{MyStackName}-DnsVerifySesDomainSesNotificationTopicF00EF47D-GEFS7RI2FKFB is invalid.`
It would require multiple custom resources, and it might start to be too complicated (at least for my needs).

I'm working on a PR for the `VerifySesEmailAddress` construct.

### PR DESCRIPTION
**Pull request by ChristopheBougere**
Fixes #214

### CODE REVIEW

**Comment by seeebiii** [comment]
@ChristopheBougere thanks for the PR! The code looks good but I'm wondering why the tests fail... see here: https://github.com/seeebiii/ses-verify-identities/pull/215/checks?check_run_id=2809021756 it seems that the region is not correctly synthesized. Could you double-check it?

**Comment by ChristopheBougere** [comment]
I can confirm that by copying the `.ts` file into my codebase, the region is synthetized well.
However, when I tried to run the test in the repo locally, I had the same error.
It seems that jest is running over the compiled JS files instead of the source TS files.
I thought that it was due to my projen setup and my way to run the tests, and that it would work in the CI.
I'll have a closer look.

**Comment by ChristopheBougere** [comment]
I dug a little on how projen works, and actually I don't think `.js` and `.d.ts` files should be committed.
I removed them in my last commit, let's see if that fix the CI

**Comment by seeebiii** [comment]
Sorry, completely forgot about it :(

**Pull request merged**
